# Generated by Django 5.1.1 on 2025-01-19 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('machine_type', models.CharField(blank=True, choices=[('Milk', 'Milk'), ('Juice', 'Juice'), ('Cooking oil', 'Cooking oil'), ('Other', 'Other')], default='Milk', max_length=255, null=True)),
                ('total_volume', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('initial_tokens', models.PositiveIntegerField(default=25)),
                ('remaining_tokens', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vending_machine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_made', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='vending.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('volume', models.FloatField(default=0.0)),
                ('token_used', models.FloatField(default=0.5)),
                ('total_amount', models.FloatField(default=0.0)),
                ('total_volume', models.FloatField(default=0.0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vending.machine')),
            ],
        ),
    ]
