# Generated by Django 5.1.1 on 2025-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
