# Generated by Django 5.1.1 on 2025-01-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0002_machine_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='remaining_tokens',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
