# Generated by Django 5.1.1 on 2025-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0003_alter_machine_remaining_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='token_pack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
