# Generated by Django 5.1.1 on 2025-01-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0004_refill_token_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refill',
            name='amount',
        ),
    ]
