# Generated by Django 5.1.5 on 2025-02-07 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0005_remove_refill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='cost_per_day',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='days_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='last_processed_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='machine',
            name='tokens_per_month',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='machine',
            name='initial_tokens',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='machine',
            name='remaining_tokens',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token_used',
            field=models.FloatField(default=1),
        ),
    ]
