# Generated by Django 5.1.5 on 2025-02-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0006_machine_cost_per_day_machine_days_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='activated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
