# Generated by Django 5.1.5 on 2025-02-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0008_alter_machine_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
