# Generated by Django 5.1.5 on 2025-02-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0009_machine_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='activation_code',
        ),
    ]
