# Generated by Django 5.1.5 on 2025-03-01 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0010_remove_machine_activation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('customers_served', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(default='Kitengela', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_shop', to='vending.shop'),
        ),
    ]
